language: node_js
node_js:
  - "6"

cache:
  directories:
  - node_modules # NPM packages

install:
  - yarn install

-before_script:
 - npm link
 - npm link teambition-sdk

script:
  - "npm run build_all"
